import type {
  BaseEndpointConfig,
  FlashEndpointConfig,
  GenerateOptions,
  JsonValue,
  LoadBalancedEndpointConfig,
  NetworkVolumeConfig,
  PodTemplateConfig,
  PythonResourceValue,
  PythonSymbol,
  QueueEndpointConfig,
  QueueHandler,
  RouteConfig,
  TsFlashConfig,
  Workers,
} from "./types.js";

const PYTHON_IMPORTS = [
  "CpuInstanceType",
  "CudaVersion",
  "DataCenter",
  "Endpoint",
  "GpuGroup",
  "GpuType",
  "NetworkVolume",
  "PodTemplate",
  "ServerlessScalerType",
];

export function generatePythonBridge(config: TsFlashConfig, options: GenerateOptions = {}): string {
  validateConfig(config);
  const banner =
    options.banner ??
    [
      "# Generated by ts-flash. Edit ts-flash.config.ts, not this file.",
      "# This bridge lets the official runpod-flash builder do the hard parts.",
    ].join("\n");

  const body: string[] = [
    banner,
    "from __future__ import annotations",
    "",
    `from runpod_flash import ${PYTHON_IMPORTS.join(", ")}`,
    "",
  ];

  for (const endpoint of config.endpoints) {
    if (endpoint.kind === "external-image") {
      body.push(...renderExternalImageEndpoint(endpoint), "");
      continue;
    }
    if (endpoint.kind === "queue") {
      body.push(...renderQueueEndpoint(endpoint), "");
      continue;
    }
    body.push(...renderLoadBalancedEndpoint(endpoint), "");
  }

  return `${body.join("\n").trimEnd()}\n`;
}

function validateConfig(config: TsFlashConfig): void {
  if (!Array.isArray(config.endpoints) || config.endpoints.length === 0) {
    throw new Error("ts-flash config must declare at least one endpoint.");
  }
  const seen = new Set<string>();
  for (const endpoint of config.endpoints) {
    if (!endpoint.name?.trim()) throw new Error("Every endpoint needs a non-empty name.");
    if (seen.has(endpoint.name)) throw new Error(`Duplicate endpoint name: ${endpoint.name}`);
    seen.add(endpoint.name);
    if (endpoint.gpu && endpoint.cpu) throw new Error(`${endpoint.name}: gpu and cpu are mutually exclusive.`);
    if (endpoint.maxConcurrency !== undefined && endpoint.maxConcurrency < 1) {
      throw new Error(`${endpoint.name}: maxConcurrency must be >= 1.`);
    }
    if (endpoint.kind === "load-balanced") {
      const routeKeys = new Set<string>();
      for (const route of endpoint.routes) {
        if (!route.path.startsWith("/")) throw new Error(`${endpoint.name}: route path must start with "/".`);
        if (route.path === "/execute" || route.path === "/ping") {
          throw new Error(`${endpoint.name}: ${route.path} is reserved by Flash.`);
        }
        const key = `${route.method}:${route.path}`;
        if (routeKeys.has(key)) throw new Error(`${endpoint.name}: duplicate route ${key}`);
        routeKeys.add(key);
      }
    }
  }
}

function renderQueueEndpoint(endpoint: QueueEndpointConfig): string[] {
  const functionName = safeIdentifier(endpoint.name);
  return [
    `@Endpoint(${renderEndpointArgs(endpoint)})`,
    `async def ${functionName}(input=None):`,
    ...indent(renderHandler(endpoint.handler, ["input"])),
  ];
}

function renderLoadBalancedEndpoint(endpoint: LoadBalancedEndpointConfig): string[] {
  const variableName = safeIdentifier(endpoint.name);
  const lines = [`${variableName} = Endpoint(${renderEndpointArgs(endpoint)})`];
  for (const item of endpoint.routes) {
    lines.push("", ...renderRoute(variableName, endpoint, item));
  }
  return lines;
}

function renderRoute(variableName: string, endpoint: LoadBalancedEndpointConfig, route: RouteConfig): string[] {
  const suffix = safeIdentifier(`${endpoint.name}_${route.method}_${route.path.replaceAll("/", "_")}`);
  return [
    `@${variableName}.${route.method}(${pythonString(route.path)})`,
    `async def ${suffix}(data=None):`,
    ...indent(renderHandler(route.handler, ["data"])),
  ];
}

function renderExternalImageEndpoint(endpoint: FlashEndpointConfig & { kind: "external-image" }): string[] {
  const variableName = safeIdentifier(endpoint.name);
  return [
    "# External-image endpoints are emitted as client/provisioning handles.",
    "# The official Flash SDK may provision them lazily on first use.",
    `${variableName} = Endpoint(${renderEndpointArgs(endpoint, { image: endpoint.image })})`,
  ];
}

function renderEndpointArgs(endpoint: BaseEndpointConfig, extra: Record<string, unknown> = {}): string {
  const args: string[] = [`name=${pythonString(endpoint.name)}`];
  appendArg(args, "gpu", endpoint.gpu, renderPythonResource);
  appendArg(args, "cpu", endpoint.cpu, renderPythonResource);
  appendArg(args, "workers", endpoint.workers, renderWorkers);
  appendArg(args, "idle_timeout", endpoint.idleTimeout, renderJson);
  appendArg(args, "dependencies", endpoint.dependencies, renderJson);
  appendArg(args, "system_dependencies", endpoint.systemDependencies, renderJson);
  appendArg(args, "accelerate_downloads", endpoint.accelerateDownloads, renderJson);
  appendArg(args, "volume", endpoint.volume, renderVolume);
  appendArg(args, "datacenter", endpoint.datacenter, renderPythonResource);
  appendArg(args, "env", endpoint.env, renderJson);
  appendArg(args, "gpu_count", endpoint.gpuCount, renderJson);
  appendArg(args, "execution_timeout_ms", endpoint.executionTimeoutMs, renderJson);
  appendArg(args, "flashboot", endpoint.flashboot, renderJson);
  appendArg(args, "scaler_type", endpoint.scalerType, renderPythonResource);
  appendArg(args, "scaler_value", endpoint.scalerValue, renderJson);
  appendArg(args, "template", endpoint.template, renderTemplate);
  appendArg(args, "min_cuda_version", endpoint.minCudaVersion, renderPythonResource);
  appendArg(args, "max_concurrency", endpoint.maxConcurrency, renderJson);
  appendArg(args, "python_version", endpoint.pythonVersion, renderJson);
  for (const [key, value] of Object.entries(extra)) {
    appendArg(args, key, value, renderJson);
  }
  return args.join(", ");
}

function renderHandler(handler: QueueHandler, defaultArgs: readonly string[]): string[] {
  if (handler.kind === "json") return [`return ${renderJson(handler.value)}`];
  if (handler.kind === "echo") return [`return ${defaultArgs[0] ?? "None"}`];

  const body = handler.body.trim();
  if (!body) throw new Error("Python handler body cannot be empty.");
  return body.split(/\r?\n/);
}

function appendArg<T>(args: string[], name: string, value: T | undefined, render: (value: NonNullable<T>) => string): void {
  if (value === undefined) return;
  args.push(`${name}=${render(value as NonNullable<T>)}`);
}

function renderWorkers(workers: Workers): string {
  if (typeof workers === "number") return String(workers);
  return `(${workers[0]}, ${workers[1]})`;
}

function renderVolume(value: NetworkVolumeConfig | readonly NetworkVolumeConfig[]): string {
  if (Array.isArray(value)) {
    return `[${(value as readonly NetworkVolumeConfig[]).map((item) => renderOneVolume(item)).join(", ")}]`;
  }
  return renderOneVolume(value as NetworkVolumeConfig);
}

function renderOneVolume(value: NetworkVolumeConfig): string {
  const args: string[] = [];
  appendArg(args, "name", value.name, renderJson);
  appendArg(args, "id", value.id, renderJson);
  appendArg(args, "size", value.size, renderJson);
  appendArg(args, "dataCenterId", value.dataCenterId, renderPythonResource);
  return `NetworkVolume(${args.join(", ")})`;
}

function renderTemplate(value: PodTemplateConfig): string {
  const args: string[] = [];
  appendArg(args, "containerDiskInGb", value.containerDiskInGb, renderJson);
  appendArg(args, "dockerArgs", value.dockerArgs, renderJson);
  appendArg(args, "ports", value.ports, renderJson);
  appendArg(args, "volumeMountPath", value.volumeMountPath, renderJson);
  return `PodTemplate(${args.join(", ")})`;
}

function renderPythonResource(value: PythonResourceValue | PythonSymbol | string): string {
  if (Array.isArray(value)) return `[${value.map((item) => renderPythonResource(item)).join(", ")}]`;
  if (isPythonSymbol(value)) return `${value.__tsFlashPythonSymbol}.${value.name}`;
  return pythonString(String(value));
}

function renderJson(value: unknown): string {
  if (typeof value === "string") return pythonString(value);
  if (typeof value === "number") return Number.isFinite(value) ? String(value) : "None";
  if (typeof value === "boolean") return value ? "True" : "False";
  if (value === null || value === undefined) return "None";
  if (Array.isArray(value)) return `[${value.map(renderJson).join(", ")}]`;
  if (typeof value === "object") {
    const entries = Object.entries(value as Record<string, JsonValue>).map(
      ([key, item]) => `${pythonString(key)}: ${renderJson(item)}`,
    );
    return `{${entries.join(", ")}}`;
  }
  return pythonString(String(value));
}

function pythonString(value: string): string {
  return JSON.stringify(value);
}

function isPythonSymbol(value: unknown): value is PythonSymbol {
  return Boolean(
    value &&
      typeof value === "object" &&
      "__tsFlashPythonSymbol" in value &&
      "name" in value &&
      typeof (value as PythonSymbol).name === "string",
  );
}

function safeIdentifier(value: string): string {
  const normalized = value.replace(/[^a-zA-Z0-9_]/g, "_").replace(/^_+/, "");
  const identifier = normalized.length > 0 ? normalized : "endpoint";
  return /^[0-9]/.test(identifier) ? `endpoint_${identifier}` : identifier;
}

function indent(lines: readonly string[]): string[] {
  return lines.map((line) => (line.trim().length === 0 ? "" : `    ${line}`));
}
